version: "3"
volumes:
  interns_pg_data:
services:
  postgres:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data"
      TZ: "UTC"
    volumes:
      #      - "$PWD/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
      - "interns_pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
